# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQrw_88JgmTUAzZzcBuna8OpHP6EcFqk
"""

print("Boa noite, Phton")

print("Spider")
print("luisa Sonza")

print("the itsy bitsy spider\climbed up the waterspout.")
print("Down came the rain and washed the spider out.")

print("My\nname\nis\nBond.", end=" ")
print("James Bond.")

print("&", "peixe", "batatas fritas", sep=", ")

print('Greg\'s book.')
print("'Greg's book.'")
print('"Greg\'s book."')
print("Greg\'s book.")

print("'Greg'\s book.'")

print('"Greg's book."')

print("eu sou\aprendizado Python")

print("faça algo legal")
print("mostre uma função sua")